apiVersion: v1
kind: Service
metadata:
  name: ssurvey-service
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30007  # Specify a port in the NodePort range (default: 30000-32767)
  selector:
    app: ssurvey
