apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey645-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: survey645
  template:
    metadata:
      labels:
        app: survey645
    spec:
      containers:
      - name: survey645
        image: saadatkhan/survey645
        ports:
        - containerPort: 8080
